### ISSUE TITLE
mjs

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Ethan-Arrowood/undici-fetch#11]
We should support mjs 👍  not sure what that requires but its something to be investigated

**Comment by alemagio** [comment]
Hi, do you think something like [this](https://github.com/fastify/fastify-autoload/blob/ed667b7dfedd1cf72095eec4fe6be88c0b85be64/index.js#L216) would be good?

**Comment by mcollina** [comment]
That'd be the minimum, 👍 !

**Comment by Ethan-Arrowood** [comment]
Since this library is targeting Node 14+, can I make it ESM out of the box?

**Comment by ronag** [comment]
That would block inclusion into undici. We still need to support node 12.

**Comment by mcollina** [comment]
cjs I'm afraid. We are still years away from a full switch.

**Comment by Ethan-Arrowood** [comment]
okay, so I should revert dropping node 12 in the headers pr I guess

**Comment by Ethan-Arrowood** [comment]
its missing stuff like https://nodejs.org/dist/latest-v15.x/docs/api/http.html#http_http_validateheadername_name and FinalizationRegistry for the eventual undici Agent integration

**Comment by mcollina** [comment]
I see the two things mostly independently!

**Comment by StarpTech** [comment]
Is there a plan to support typescript? Currently, it's not possible to require or import a raw .mjs module.

**Comment by Ethan-Arrowood** [comment]
TypeScript will most likely be provided via hand rolled type definitions. Luckily fetch types aren't likely to change much overtime

**Comment by StarpTech** [comment]
ok, maybe I misunderstood the issue. I thought you want to provide this package es `"type: "module"`?

**Comment by Ethan-Arrowood** [comment]
Ahh I see; yes in the future I'd love to make this package entirely ESM. But as Matteo noted that would restrict adoption so for now I'll stick to CJS with some MJS adapter and make the move to ESM later

**Comment by StarpTech** [comment]
Great 👍

**Comment by Ethan-Arrowood** [comment]
undici-fetch is now apart of [undici](https://github.com/nodejs/undici) core 🚀 as a result this repo is being archived and all current PRs and issues are being closed out. 

Check out the [undici 4.4.1](https://github.com/nodejs/undici/releases/tag/v4.4.1) for the latest fetch API
