### ISSUE TITLE
Integrate node-fetch test suite

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Ethan-Arrowood/undici-fetch#19]
Would be cool to see if we can run node-fetch's test suite against this implementation to find differences.

I don't know if I'd want this to be apart of the normal test script but maybe a separate utility?

**Comment by galvez** [comment]
@Ethan-Arrowood I can pick this up if no one else started on it yet.

**Comment by Ethan-Arrowood** [comment]
Go for it! Please keep their tests in one directory, maybe `tests/node-fetch/`, and an independent npm script to execute them, maybe `test:node-fetch`. Thank you!

**Comment by Ethan-Arrowood** [comment]
undici-fetch is now apart of [undici](https://github.com/nodejs/undici) core 🚀 as a result this repo is being archived and all current PRs and issues are being closed out. 

Check out the [undici 4.4.1](https://github.com/nodejs/undici/releases/tag/v4.4.1) for the latest fetch API
