### ISSUE TITLE
Rethink client map

### ISSUE THREAD

**Issue by timdp** [Ethan-Arrowood/undici-fetch#31]
Currently, an internal Map holds on to the client for every previously seen origin. This won't scale. 

I'd like to be able to use undici-fetch in a context where a long-running application makes calls to a large number of arbitrary URLs. In this case, the Map will keep growing, creating a memory leak. I could periodically flush it, but that's not very intelligent. Some origins will occur frequently, so I'd like to reuse the clients for those.

Suggested approaches:
1. Replace the Map with an LRU cache with a sensible maximum size. Allow `buildFetch` to override the size.
2. Keep the Map but let `buildFetch` override the client creation and disposal behaviors.
3. Remove the Map and externalize all client caching behavior.

I'm leaning toward 3, because 1 and 2, as well as the current implementation, make too many assumptions on the use case. While my use case is that I want to run it at scale, maybe far more often, people will use it for a single request.

An additional benefit of option 3 would be that the nonstandard `fetch.close` can be removed as it's the implicit default: make a single request and clean up after yourself.

Conversely, if people _do_ want client caching, it'll be tedious to maintain the cache themselves. However, it'd be trivial to publish a separate package that exposes the same API but with client reuse.

Thoughts?

**Comment by mcollina** [comment]
undici-fetch should move to the new Agent APIs of Undici. It already takes care of this.

**Comment by timdp** [comment]
@mcollina Thanks. Doesn't the agent cache suffer from a similar issue though? It's great that it cleans up unused refs. However, I assume it holds on to idle connections for a while before closing them, right? Consequently, couldn't the number of idle connections and therefore pools still spike?

**Comment by mcollina** [comment]
You can control how long to keep an idle connection via options.

**Comment by Ethan-Arrowood** [comment]
We should move to Undici agent, but I also have some more ideas to make undici-fetch more usable for distinct use cases. For example if a use does expect to use fetch for only one origin, we should skip the whole agent part and just have the internal client set to a Pool instance connected to that given origin.

**Comment by Ethan-Arrowood** [comment]
closed by #43
