### ISSUE TITLE
support for string body

### ISSUE THREAD

**Issue by PabloSzx** [Ethan-Arrowood/undici-fetch#40]
While trying to use it I encountered that it doesn't accept a string as body as the regular fetch, and when trying to transform the string to readable, it complains about content-length mismatch.

Any guide/example in how to do it is necessary, no examples show any body parameter usage

**Comment by Ethan-Arrowood** [comment]
Here is an example POST request: https://github.com/Ethan-Arrowood/undici-fetch/blob/f5e712512a5f37bf1520ffde415ff7a949cb066a/test/fetch.js#L57

In my new api (branch `new-api`) will have better body support.

**Comment by Ethan-Arrowood** [comment]
closed with #43
