### ISSUE TITLE
Support redirects

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Ethan-Arrowood/undici-fetch#51]
Need to add tests for redirect support and maybe reconfigure undici to support it. Fetch has its own redirect flow that needs to be considered as well.

**Comment by ronag** [comment]
undici now has redirect support

**Comment by Ethan-Arrowood** [comment]
undici-fetch is now apart of [undici](https://github.com/nodejs/undici) core 🚀 as a result this repo is being archived and all current PRs and issues are being closed out. 

Check out the [undici 4.4.1](https://github.com/nodejs/undici/releases/tag/v4.4.1) for the latest fetch API
