### ISSUE TITLE
statusText is "raw"

### ISSUE THREAD

**Issue by annevk** [Ethan-Arrowood/undici-fetch#53]
Per spec statusText can be anything the server decides to set it too, e.g., for a `200 BLAH` response it'd be `BLAH`. At least from the documentation it doesn't seem like this would match that:

> A property representing the status of the response instance based on http.STATUS_CODES.

**Comment by Ethan-Arrowood** [comment]
Good catch, I think the code accurately reflects the spec (you can specify your own status code for a custom Response instance), but the docs need updating

**Comment by Ethan-Arrowood** [comment]
Fixed docs on main ty for the issue!
