### ISSUE TITLE
re-release using undici v4

### ISSUE THREAD

**Issue by PabloSzx** [Ethan-Arrowood/undici-fetch#58]
undici v4.0.0 was released 7 days ago, and the update in the package.json was made 5 days ago https://github.com/Ethan-Arrowood/undici-fetch/commit/bc6104329ed73973afa3008dd27008f229c326de#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519, but there hasn't been any release of undici-fetch with the changes https://www.npmjs.com/package/undici-fetch

**Comment by Ethan-Arrowood** [comment]
I'll put out rc 2 today 👍

**Comment by Ethan-Arrowood** [comment]
done :) https://github.com/Ethan-Arrowood/undici-fetch/releases/tag/v1.0.0-rc.2
