### ISSUE TITLE
headers values can be an array

### ISSUE THREAD

**Issue by KhafraDev** [Ethan-Arrowood/undici-fetch#60]
When using the module to fetch an OAUTH token from twitter's api, they return a `set-cookie` header that undici parses as an array. 

The typings support it as well:
https://github.com/nodejs/undici/blob/8d968591620f6b89348ad823f7b82d1ecd5e528a/types/dispatcher.d.ts#L47
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2563cecd0398fd9337b2806059446fb9d29abec2/types/node/http.d.ts#L7

I have no idea how to replicate the issue without using twitter's API that requires authorization to use. Not only this I don't really know how you would want to handle this since I know you put a lot of time into increasing header performance.

edit: forgot to mention that when the values are an array it throws an error when normalizing them

**Comment by Ethan-Arrowood** [comment]
Can you share some debugging info? Undici-fetch should be able to support array based headers

**Comment by KhafraDev** [comment]
Here's the code that I mentioned before (sadly the API need authorization and I can't replicate the issue anywhere else I've tried):

```js
const getTwitterOAUTH = async () => {
    const creds = Buffer.from(`${process.env.TWITTER_API}:${process.env.TWITTER_API_SECRET}`).toString('base64');
    const r = await fetch('https://api.twitter.com/oauth2/token', {
        method: 'POST',
        body: 'grant_type=client_credentials',
        headers: {
            Authorization: `Basic ${creds}`,
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
        }
    });
    const j = await r.json() as OAuth;
    return `${j.token_type} ${j.access_token}`;
}
```

The error comes from this line:
https://github.com/Ethan-Arrowood/undici-fetch/blob/f01bd2e99149ff823c32b6007213d8bedb46d12b/src/headers.js#L15
because <array>.replace isn't a function

**Comment by Ethan-Arrowood** [comment]
So the header value from undici was an array; hmm 🤔 

@ronag are you aware of headers being returned from something as an array? I assumed by spec headers are always returned as a string.

**Comment by mcollina** [comment]
This is the same behavior of Node.js.

**Comment by ronag** [comment]
Multiple values for same header will become an array.
