### ISSUE TITLE
type issues

### ISSUE THREAD

**Issue by KhafraDev** [Ethan-Arrowood/undici-fetch#62]
Typings seem to be missing some properties and other issues I've encountered:

[Response](https://fetch.spec.whatwg.org/#response-class):
- Property 'url' does not exist on type 'Response<unknown>'.
- Property 'redirected' does not exist on type 'Response<unknown>'.

Other issues:
- Headers, Request, and Response are exported as types which means typescript disallows you constructing them for yourself.
```ts
import fetch, { Headers } from 'undici-fetch';

const headers = new Headers({ a: 'b' }); // 'Headers' cannot be used as a value because it was exported using 'export type'.
```

**Comment by Ethan-Arrowood** [comment]
Good catch! This definitely needs fixing

**Comment by joaopedrocampos** [comment]
@Ethan-Arrowood hey, if possible I would like to get this fix! 🙏

**Comment by joaopedrocampos** [comment]
Hey @Ethan-Arrowood! Do you think we should close this issue now since the MR is merged?
