### ISSUE TITLE
WebStreams has landed in Node

### ISSUE THREAD

**Issue by ronag** [Ethan-Arrowood/undici-fetch#65]
Webstreams have landed and will probably be included in on 16. Should we drop 14 support?

**Comment by ronag** [comment]
Also Blob's have landed as well.

**Comment by Ethan-Arrowood** [comment]
Yeah once webstreams and blob are stable ill be dropping 14 support

**Comment by jimmywarting** [comment]
Start preparing support for it using something like [fetch-blob](https://github.com/node-fetch/fetch-blob) and [https://github.com/MattiasBuelens/web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill)?

could easily be dropped later.
